name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4

      run: docker build -t back -f ./back/dockerfile ./back --tag my-image-name:$(date +%s)

      - name: UploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-build-output
        path: ./back/docker-image.tar

